{% set version = "1.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dtplyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dtplyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dtplyr/dtplyr_{{ version }}.tar.gz
  sha256: a5a9689a640b8bd1274519af220c33deaa3919654acac4ebdff1ff365cc8d6e5

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-crayon
    - r-data.table >=1.13.0
    - r-dplyr >=1.0.3
    - r-ellipsis
    - r-glue
    - r-lifecycle
    - r-rlang
    - r-tibble
    - r-tidyselect
    - r-vctrs

  run:
    - r-base
    - r-crayon
    - r-data.table >=1.13.0
    - r-dplyr >=1.0.3
    - r-ellipsis
    - r-glue
    - r-lifecycle
    - r-rlang
    - r-tibble
    - r-tidyselect
    - r-vctrs

test:
  commands:
    - $R -e "library('dtplyr')"           # [not win]
    - "\"%R%\" -e \"library('dtplyr')\""  # [win]

about:
  home: https://github.com/hadley/dtplyr
  license: MIT
  summary: This implements the data table back-end for 'dplyr' so that you can seamlessly use data table and 'dplyr' together.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: dtplyr
# Title: Data Table Back-End for 'dplyr'
# Version: 0.0.3
# Authors@R: c( person("Lionel", "Henry", , "lionel@rstudio.com", role = "cre"), person("Hadley", "Wickham", , "hadley@rstudio.com", role = "aut"), person("RStudio", role = "cph") )
# Description: This implements the data table back-end for 'dplyr' so that you can seamlessly use data table and 'dplyr' together.
# License: GPL (>= 2)
# Imports: dplyr (>= 0.5.0), data.table (>= 1.9.6), lazyeval, rlang
# Suggests: Lahman, nycflights13, testthat, covr
# LazyData: true
# RoxygenNote: 6.1.1
# URL: https://github.com/hadley/dtplyr
# BugReports: https://github.com/hadley/dtplyr/issues
# NeedsCompilation: no
# Packaged: 2019-02-25 19:14:43 UTC; lionel
# Author: Lionel Henry [cre], Hadley Wickham [aut], RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-02-25 19:40:03 UTC
