appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kOpdyzeU89L+6nOFXrHpaEYZvKeoPt7M3DAEqoOwCrL/KeJDIN6PR+Ve9f4RLbBT9g7ZoeAo8rE6NPDb+yLAbb49mG/icrY/6Mb+TeoY1m4EgzVPx0qFUdk4whFMX96PCwDYeEkQ8DPQdI1AK7llLxAUrn6rlsAGqizgtqbo1PENPyGunhmRB2jF5Zppxyw8lzWTcqgvSt7O6GsDsd4EyXE5R+7dUlvijFbdC2Tbs47qpDEc796+B9mj8/NMGQE4zK/KD+CAR1yiUSy+fxEPvpr8xZlY0aWf+3NcShyzukAB81RAuf0MikDDIn0zZ24tnz+7wHyVqHfOg2+3Wkf7lasMRreabI2NFqNJSaDw+R41J7aKXDtR+2w07XcDznTnfqTakFK7JJeAy1mIM7qGwb+SvshnIolKF1gTMQ0cji3yf0y1l6T7SbPwIbFbjotgXe0VXSH9BPrXZBMIQuCtuAAayZ8/g63FuqszivUtbc6cpbbcrtZL21u230TPFABrvNNIAuXoR7+6EQEcAX+FJbJvyhhDaYCBguMHd2PN/fTov5gjBhmyzr6sqeYqLknqfrJXXpM1sFxtLKN/03HhC3kD0iK1fF1lsP9hfXhGYzsK5sjzMtpYhSEYaJUtFcO1JOJjMm13Y7EDpyo0mPDksPmHCaWw1jChO0+1J3K4a5w=}
bot:
  automerge: true
